name: "ye humari testing pipeline hai"

on:
  workflow_dispatch:   # manual run karta hai

permissions:
  id-token: write
  contents: read

# on:
#   push:
#     branches:
#       - 'main'
#       - 'feature/**'

jobs:
  azure_resource_create:
    runs-on: self-hosted
    steps:
      - name: Checkout for git clone
        uses: actions/checkout@v6.0.1

      - name: Install Azure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl apt-transport-https lsb-release gnupg
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | \
            gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
          AZ_REPO=$(lsb_release -cs)
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | \
            sudo tee /etc/apt/sources.list.d/azure-cli.list
          sudo apt-get update
          sudo apt-get install -y azure-cli
                    
      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

  
      
      

     
