name: "ye humari testing pipeline hai"

# on:
#   workflow_dispatch:

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - 'main'
      # - 'feature/**'

jobs:
  azure_resource_create:
    runs-on: self-hosted
    steps:
      - name: Checkout for git clone
        uses: actions/checkout@v6.0.1

      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Run TFLint
        run: tflint --chdir=environment/dev || true
      

      - name: Terraform Init
        run: terraform init
        working-directory: environment/dev

      - name: Terraform validate
        run: terraform validate
        working-directory: environment/dev

      - name: Terraform Plan
        run: terraform plan
        working-directory: environment/dev

  
      
      

     
