name: "ye humari testing pipeline hai"

on:
  workflow_dispatch:   # manual run karta hai

permissions:
  id-token: write
  contents: read

# on:
#   push:
#     branches:
#       - 'main'
#       - 'feature/**'

jobs:
  azure_resource_create:
    runs-on: self-hosted
    steps:
      - name: Checkout for git clone
        uses: actions/checkout@v6.0.1

      - name: Azure CLI Action
        uses: Azure/cli@v2.2.0
                    
      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

  
      
      

     
