name: "ye humari testing pipeline hai"

on:
  workflow_dispatch:   # manual run karta hai

permissions:
  id-token: write
  contents: read

# on:
#   push:
#     branches:
#       - 'main'
#       - 'feature/**'

jobs:
  azure_resource_create:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
        

